package com.test.mavendemo1;



/**
 * MoneyTable generated by hbm2java
 */
public class MoneyTable  implements java.io.Serializable {


     private String orderId;
     private String productName;
     private int amount;
     private String productImageUrl;
     private String confirmUrl;
     private String currency;

    public MoneyTable() {
    }

    public MoneyTable(String orderId, String productName, int amount, String productImageUrl, String confirmUrl, String currency) {
       this.orderId = orderId;
       this.productName = productName;
       this.amount = amount;
       this.productImageUrl = productImageUrl;
       this.confirmUrl = confirmUrl;
       this.currency = currency;
    }
   
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public String getProductImageUrl() {
        return this.productImageUrl;
    }
    
    public void setProductImageUrl(String productImageUrl) {
        this.productImageUrl = productImageUrl;
    }
    public String getConfirmUrl() {
        return this.confirmUrl;
    }
    
    public void setConfirmUrl(String confirmUrl) {
        this.confirmUrl = confirmUrl;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


