package model;
// Generated 2020/7/30 ¤U¤È 08:29:48 by Hibernate Tools 4.3.1



/**
 * Personallnformation generated by hbm2java
 */
public class Personallnformation  implements java.io.Serializable {


     private String pid;
     private String username;
     private String email;
     private String password;
     private String payList;

    public Personallnformation() {
    }

	
    public Personallnformation(String pid, String email, String password, String payList) {
        this.pid = pid;
        this.email = email;
        this.password = password;
        this.payList = payList;
    }
    public Personallnformation(String pid, String username, String email, String password, String payList) {
       this.pid = pid;
       this.username = username;
       this.email = email;
       this.password = password;
       this.payList = payList;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPayList() {
        return this.payList;
    }
    
    public void setPayList(String payList) {
        this.payList = payList;
    }




}


